### ISSUE TITLE
ResideMenu的bug

### ISSUE THREAD

**Issue by zz234807** [handsomezhou/XDesktopHelper#1]
ResideMenu类里面->
fitSystemWindows(Rect insets)方法里面判断虚拟按键->
if (!hasBackKey || !hasHomeKey) 这个判断反了，应该改成if (hasBackKey || hasHomeKey)。
否则虚拟按键的高度没有被计算进去。

**Comment by handsomezhou** [comment]
建议给原作者提bug  https://github.com/SpecialCyCi/AndroidResideMenu
